import type { OrgDocument } from './model';
export const initialDocument: OrgDocument = {
  schemaVersion: 1,
  company: 'Ubiqedge',
  version: '0.2',
  createdBy: 'Initial source import',
  createdDate: '2026-09-02T12:48:37.125Z',
  updatedBy: 'Requested leadership update',
  updatedDate: '2026-09-03T00:00:00.000Z',
  validatedBy: '',
  validatedDate: '',
  approvedBy: '',
  approvalDate: '',
  reviewDate: '2026-10-02',
  governance: { boardName: 'Company Board', ceoId: '3' },
  employees: [
    {
      id: '1',
      name: 'Hetvi Manish Shah',
      alias: 'Hetvi Shah',
      title: 'COO',
      department: 'Management',
      managerId: '3',
      managerReference: '',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'hetvi@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '2',
      name: 'Archit Rajeev Khandelwal',
      alias: 'Archit Khandelwal',
      title: 'CSO',
      department: 'Management',
      managerId: '3',
      managerReference: '',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'archit@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '3',
      name: 'Visat Subodh Patel',
      alias: 'Visat Patel',
      title: 'CEO',
      department: 'Management',
      managerId: '',
      managerReference: '',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'visat@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: true,
      notes: '',
    },
    {
      id: '4',
      name: 'Akhilesh Parashram Thorat',
      alias: 'Akhilesh thorat',
      title: 'CTO',
      department: 'Management',
      managerId: '3',
      managerReference: '',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'akhilesh@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '5',
      name: 'Sushil Gopal Kumawat',
      alias: 'Sushil',
      title: 'Software Development Engineer 2 (SDE 2)',
      department: 'Software',
      managerId: '25',
      managerReference: 'Ozair Khatri',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'sushil.kumawat@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '6',
      name: 'Meraj Muzammil Shaikh',
      alias: 'Meraj',
      title: 'Embedded Systems Engineer',
      department: 'Product & Solution',
      managerId: '4',
      managerReference: 'Akhilesh Parashram Thorat',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'meraj.shaikh@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '7',
      name: 'Rajdip Saha',
      alias: 'Rajdip',
      title: "Founder's Office Lead",
      department: 'Founder Office',
      managerId: '3',
      managerReference: 'Visat Subodh Patel',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'rajdip.saha@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '8',
      name: 'Niyazuddin Sarfuddin Khan',
      alias: 'Niyazuddin',
      title: 'Hardware Team Lead',
      department: 'Product & Solution',
      managerId: '4',
      managerReference: 'Akhilesh Parashram Thorat',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'niyazuddin.khan@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '9',
      name: 'Albert Anthony Suvarna',
      alias: 'Albert',
      title: 'Production Engineer',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'albert.suvarna@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '10',
      name: 'Rakesh Ravindra Ambekar',
      alias: 'Rakesh',
      title: 'Office Assistant',
      department: 'Admin',
      managerId: '1',
      managerReference: 'Hetvi Shah',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'rakesh.ambekar@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '11',
      name: 'Pramod Ramesh Kumar Pandit',
      alias: 'Pramod',
      title: 'Production Technician',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: '',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '14',
      name: 'Tejal Yashwant Kondalkar',
      alias: 'Tejal',
      title: 'IoT Technical Support Engineer',
      department: 'Support',
      managerId: '1',
      managerReference: 'Hetvi Shah',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'tejal.kondalkar@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '17',
      name: 'Sanket Ravi Mane',
      alias: 'Sanket',
      title: 'Quality Control Engineer',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'sanket.mane@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '18',
      name: 'Omprakash Ghansham Mahto',
      alias: 'Omprakash',
      title: 'Production Technician',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: '',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '19',
      name: 'Jeel Naishadh Ramani',
      alias: 'Jeel',
      title: 'Embedded Systems Engineer',
      department: 'Product & Solution',
      managerId: '4',
      managerReference: 'Akhilesh Parashram Thorat',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'jeel.ramani@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '20',
      name: 'Shubham Surendra Surve',
      alias: 'Shubham',
      title: 'Production Associate',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'Shubham.surve@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '23',
      name: 'Ambadas Shivsharan Sangoli',
      alias: 'Ambadas',
      title: 'Sales Head',
      department: 'Sales & Marketing',
      managerId: '3',
      managerReference: 'Visat Subodh Patel',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'ambadas.sangoli@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '24',
      name: 'Trupti Minil Awade',
      alias: 'Trupti',
      title: 'Senior HR Generalist',
      department: 'Admin',
      managerId: '1',
      managerReference: 'Hetvi Shah',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'trupti.awade@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '25',
      name: 'Ozair M Salim Khatri',
      alias: 'Ozair',
      title: 'Senior Engineering Manager',
      department: 'Software',
      managerId: '4',
      managerReference: 'Akhilesh Parashram Thorat',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'ozair.khatri@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '27',
      name: 'Anoop Santosh Upadhyay',
      alias: 'Anoop',
      title: 'Hardware Design Engineer',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'anoop.upadhyay@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '29',
      name: 'Atul Ashok Tulaskar',
      alias: 'Atul',
      title: 'MIS / Data Analyst',
      department: 'Founder Office',
      managerId: '7',
      managerReference: 'Rajdip Saha',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'atul.tulaskar@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '32',
      name: 'Tushar Sharad Shelke',
      alias: 'Tushar',
      title: 'SR. Finance Executive',
      department: 'Admin',
      managerId: '3',
      managerReference: 'Visat Subodh Patel',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'tushar.shelke@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '33',
      name: 'Abdallah Mubeen Dalvi',
      alias: 'Abdallah',
      title: 'Growth & Marketing Strategist',
      department: 'Founder Office',
      managerId: '7',
      managerReference: 'Rajdip Saha',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'abdallah.dalvi@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '34',
      name: 'Rutvik Kailas Sonawane',
      alias: 'Rutvik',
      title: 'Software Operations Executive (IoT Integrations)',
      department: 'Support',
      managerId: '1',
      managerReference: 'Hetvi Shah',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'rutvik.sonawane@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '35',
      name: 'Praful Kishor Vaidya',
      alias: 'Praful',
      title: 'Associate Engineer - Embedded',
      department: 'Product & Solution',
      managerId: '4',
      managerReference: 'Akhilesh Parashram Thorat',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'praful.vaidya@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '36',
      name: 'Ansh Valjibhai Dobariya',
      alias: 'Ansh',
      title: 'Associate Engineer - Embedded',
      department: 'Product & Solution',
      managerId: '4',
      managerReference: 'Akhilesh Parashram Thorat',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'ansh.dobariya@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '37',
      name: 'Shubham Subhash Yadav',
      alias: 'Shubham',
      title: 'Hardware Design Engineer',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'shubham.yadav@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '38',
      name: 'Sameer Ravindra Gorivale',
      alias: 'Sameer',
      title: 'Store Executive',
      department: 'Store',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'store@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '40',
      name: 'Prathmesh Hemant Walavalkar',
      alias: 'Prathmesh',
      title: 'IoT Technical Support Engineer',
      department: 'Support',
      managerId: '1',
      managerReference: 'Hetvi Shah',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'prathmesh.walavalkar@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '42',
      name: 'Vrushali Vinod Rolkar',
      alias: 'Vrushali',
      title: 'Quality Control Engineer',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'vrushali.rolkar@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '43',
      name: 'Soniya Jaywant Kirdat',
      alias: 'Soniya',
      title: 'Sales Coordinator',
      department: 'Founder Office',
      managerId: '7',
      managerReference: 'Rajdip Saha',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'soniya.kirdat@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '44',
      name: 'Jyoti Dilip Anbhule',
      alias: 'Jyoti',
      title: 'JR. Full Stack Developer',
      department: 'Software',
      managerId: '25',
      managerReference: 'Ozair Khatri',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'jyoti.anbhule@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '45',
      name: 'Faiz Zahir Shaikh',
      alias: 'Faiz',
      title: 'Production Technician',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'faiz.shaikh@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '47',
      name: 'Shubham Maheshkumar Yadav',
      alias: 'Shubham',
      title: 'Quality Control Engineer',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'shubham.m.yadav@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '48',
      name: 'Sagar Keshav Uparkar',
      alias: 'Sagar',
      title: 'Field Technician',
      department: 'Product & Solution',
      managerId: '2',
      managerReference: 'Archit Rajeev Khandelwal',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'sagar.uparakar@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '50',
      name: 'Sushree Barsalin Panda',
      alias: 'Sushree',
      title: 'Creative Designer',
      department: 'Founder Office',
      managerId: '7',
      managerReference: 'Rajdip Saha',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'shushree.panda@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '28',
      name: 'Abdullah Imtiyaz Shethwala',
      alias: 'Abdullah Shethwala',
      title: 'Jr. Data Engineer',
      department: 'Founder Office',
      managerId: '7',
      managerReference: 'Rajdip Saha',
      functionalIds: ['4'],
      functionalReference: 'Akhilesh Thorat',
      status: 'Active',
      email: 'abdullah.shethwala@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '53',
      name: 'Krupali Govind Jawalkar',
      alias: 'Krupali',
      title: 'ERP Management Associate',
      department: 'Founder Office',
      managerId: '7',
      managerReference: 'Rajdip Saha',
      functionalIds: ['4'],
      functionalReference: 'Akhilesh Thorat',
      status: 'Active',
      email: 'krupali.jawalkar@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '51',
      name: 'Akshay Jalinder Shelar',
      alias: 'Akshay',
      title: 'Product Test Engineer',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'akshay.shelar@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '52',
      name: 'Yash Ganesh Kadam',
      alias: 'Yash',
      title: 'Production Technician',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'yash.kadam@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '54',
      name: 'Sakshi Shashikant Gurav',
      alias: 'Sakshi',
      title: 'Talent Acquisition Associate',
      department: 'Admin',
      managerId: '24',
      managerReference: 'Trupti Awade',
      functionalIds: ['1'],
      functionalReference: 'Hetvi Shah',
      status: 'Active',
      email: 'sakshigurav76538@gmail.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '26',
      name: 'Sapana Vinod Rai',
      alias: 'Sapana',
      title: 'Jr. Accounts Executive',
      department: 'Admin',
      managerId: '32',
      managerReference: 'Tushar sharad Shelke',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'sapna.rai@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '55',
      name: 'Adarsh Dhananjay Maurya',
      alias: 'Adarsh',
      title: 'Software Operations Executive',
      department: 'Software',
      managerId: '25',
      managerReference: 'Ozair Khatri',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'adarsh.maurya@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '56',
      name: 'Vinanti Ravindra Mhatre',
      alias: 'Vinanti',
      title: 'Production Technician - Firmware',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'vinanti.mhatre@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '57',
      name: 'Sejal Rajendra Saldur',
      alias: 'Sejal',
      title: 'Production Technician',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'sejal.saldur@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '58',
      name: 'Franciska Thomsan Peter',
      alias: 'Franciska',
      title: 'HR Executive',
      department: 'Admin',
      managerId: '24',
      managerReference: 'Trupti Awade',
      functionalIds: ['1'],
      functionalReference: 'Hetvi Shah',
      status: 'Active',
      email: 'franciska.peter@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '59',
      name: 'Divakar Hem Thakur',
      alias: 'Divakar',
      title: 'Senior Embedded Engineer',
      department: 'Product & Solution',
      managerId: '4',
      managerReference: 'Akhilesh Parashram Thorat',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'diwakar.thakur@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '60',
      name: 'Rishikesh Dharmendra Singh',
      alias: 'Rishikesh',
      title: "Founder's Office Intern",
      department: 'Founder Office',
      managerId: '7',
      managerReference: 'Rajdip Saha',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'rishikesh.singh@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '61',
      name: 'Kapil Prahlad Kumavat',
      alias: 'Kapil',
      title: 'Finance Controller',
      department: 'Admin',
      managerId: '3',
      managerReference: 'Visat Subodh Patel',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'kapil.kumavat@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '62',
      name: 'Mayuri Dattatraya Deokar',
      alias: 'Mayuri',
      title: 'Research Associate-Edge Embedded Systems',
      department: 'Product & Solution',
      managerId: '4',
      managerReference: 'Akhilesh Parashram Thorat',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'mayuri.deokar@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '63',
      name: 'Sandeep Triloki Mourya',
      alias: 'Sandeep',
      title: 'Software Developement Engineer 2 (SDE ll)',
      department: 'Software',
      managerId: '25',
      managerReference: 'Ozair Khatri',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'sandeep.mourya@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '64',
      name: 'Sujal Maganlal Jain',
      alias: 'Sujal',
      title: 'AI Intern',
      department: 'Software',
      managerId: '25',
      managerReference: 'Ozair Khatri',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'sujal.jain@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '65',
      name: 'Sagar Babu Gavali',
      alias: 'Sagar',
      title: 'Office Assistant',
      department: 'Admin',
      managerId: '1',
      managerReference: 'Hetvi Shah',
      functionalIds: [],
      functionalReference: '',
      status: 'Active',
      email: 'sagar.gavali@ubiqedge.com',
      source: 'Active Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: 'VSS432',
      name: 'Ashish',
      alias: '',
      title: '',
      department: '',
      managerId: '',
      managerReference: '',
      functionalIds: [],
      functionalReference: '',
      status: 'Needs review',
      email: '',
      source: 'Active Emp',
      sourceStatus: '',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '41',
      name: 'Nivedita Sharma',
      alias: 'Nivedita',
      title: 'ERP & Subscription Associate',
      department: 'Founder Office',
      managerId: '7',
      managerReference: 'Rajdip Saha',
      functionalIds: [],
      functionalReference: '',
      status: 'Inactive',
      email: 'nivedita.sharma@ubiqedge.com',
      source: 'Inactive Emp',
      sourceStatus: 'Abscond',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '46',
      name: 'Vishal Muthu Nadar',
      alias: 'Vishal',
      title: 'Recruitment Associate',
      department: 'Admin',
      managerId: '24',
      managerReference: 'Trupti Awade',
      functionalIds: [],
      functionalReference: '',
      status: 'Inactive',
      email: 'vishal.nadar@ubiqedge.com',
      source: 'Inactive Emp',
      sourceStatus: 'Abscond',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '16',
      name: 'Lubdha Gurunath Pashte',
      alias: 'Lubdha',
      title: 'Software Development Engineer',
      department: 'Software Team',
      managerId: '25',
      managerReference: 'Ozair Khatri',
      functionalIds: [],
      functionalReference: '',
      status: 'Inactive',
      email: 'lubdha.pashte@ubiqedge.com',
      source: 'Inactive Emp',
      sourceStatus: 'Resigned',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '49',
      name: 'Shyaan Nakhwa',
      alias: 'Shyaan',
      title: 'Sales and Marketing Intern',
      department: 'Founder Office',
      managerId: '7',
      managerReference: 'Rajdip Saha',
      functionalIds: [],
      functionalReference: '',
      status: 'Needs review',
      email: '',
      source: 'Inactive Emp',
      sourceStatus: 'Intern',
      rootConfirmed: false,
      notes: '',
    },
    {
      id: '21',
      name: 'Meer Lubnan Mazhar Ali',
      alias: 'Meer',
      title: 'Production Engineer',
      department: 'Product & Solution',
      managerId: '8',
      managerReference: 'Niyazuddin Sarfuddin Khan',
      functionalIds: [],
      functionalReference: '',
      status: 'Needs review',
      email: 'lubnan.meer@ubiqedge.com',
      source: 'Inactive Emp',
      sourceStatus: 'Active',
      rootConfirmed: false,
      notes: '',
    },
  ],
  proposals: [
    {
      name: 'Executive Leadership',
      roles: 'CEO, Co-Founder(s), CXO(s)',
      summary:
        'Provides overall company leadership, strategic direction, decision-making, governance and business oversight.',
    },
    {
      name: 'Growth, Marketing & Creative',
      roles:
        "Founder's office,Growth & Marketing Strategist, Creative Designer",
      summary:
        'Handles brand building, marketing, communication, content, creative design, lead generation and market visibility.',
    },
    {
      name: 'Sales',
      roles: 'Sales Head, Sales Team',
      summary:
        'Responsible for customer acquisition, sales targets, proposals, negotiations, conversions and revenue generation.',
    },
    {
      name: 'Business Development & Business Operations',
      roles:
        'Business Development Executives, MIS Executive, ERP Management Associate',
      summary:
        'Handles business opportunities, partnerships, business coordination, MIS/reporting, ERP processes and internal business operations.',
    },
    {
      name: 'Hardware Engineering & Production',
      roles:
        'Hardware Lead, Hardware Designers, Embedded Systems Engineers, Production Engineer, Production Technicians',
      summary:
        'Covers hardware design, embedded systems, product development, testing, production engineering and manufacturing/assembly.',
    },
    {
      name: 'Software Engineering & Operations',
      roles:
        'Software Manager, Software Developers, Software Operations Engineer, Data Engineer',
      summary:
        'Responsible for software development, platform operations, data engineering, technical infrastructure, maintenance and software systems.',
    },
    {
      name: 'Field & Customer Support',
      roles:
        'Support Team, Field Technicians, IoT Integrations � Software Ops Executive',
      summary:
        'Handles customer support, IoT integrations from the customer/service perspective, field installation, troubleshooting, maintenance and issue resolution.',
    },
    {
      name: 'Human Resources & Administration',
      roles: 'Senior HR Generalist / HR Team, Office Assistant',
      summary:
        'Manages recruitment, employee lifecycle, HR policies, documentation, attendance, employee coordination and office administration.',
    },
    {
      name: 'Finance & Accounts',
      roles: 'Finance Controller, Accounts Executive',
      summary:
        'Manages accounting, financial planning, payments, billing, statutory compliance, financial reporting and controls.',
    },
    {
      name: 'Operations & Supply Chain',
      roles:
        'Procurement, Stores/Warehouse, Logistics, Inventory, Dispatch & Delivery',
      summary:
        'Future function covering procurement, inventory, warehousing, logistics, dispatch, delivery and supply-chain coordination.',
    },
  ],
  functions: [
    {
      name: 'Management',
      summary:
        'Current roles: COO; CSO; CEO; CTO. Function description to be confirmed by HR.',
    },
    {
      name: 'Software',
      summary:
        'Current roles: Software Development Engineer 2 (SDE 2); Senior Engineering Manager; JR. Full Stack Developer; Software Operations Executive; Software Developement Engineer 2 (SDE ll); AI Intern. Function description to be confirmed by HR.',
    },
    {
      name: 'Product & Solution',
      summary:
        'Current roles: Embedded Systems Engineer; Hardware Team Lead; Production Engineer; Production Technician; Quality Control Engineer; Production Associate; Hardware Design Engineer; Associate Engineer - Embedded; Field Technician; Product Test Engineer; Production Technician - Firmware; Senior Embedded Engineer; Research Associate-Edge Embedded Systems. Function description to be confirmed by HR.',
    },
    {
      name: 'Founder Office',
      summary:
        "Current roles: Founder's Office Lead; MIS / Data Analyst; Growth & Marketing Strategist; Sales Coordinator; Creative Designer; Jr. Data Engineer; ERP Management Associate; Founder's Office Intern. Function description to be confirmed by HR.",
    },
    {
      name: 'Admin',
      summary:
        'Current roles: Office Assistant; Senior HR Generalist; SR. Finance Executive; Talent Acquisition Associate; Jr. Accounts Executive; HR Executive; Finance Controller. Function description to be confirmed by HR.',
    },
    {
      name: 'Support',
      summary:
        'Current roles: IoT Technical Support Engineer; Software Operations Executive (IoT Integrations). Function description to be confirmed by HR.',
    },
    {
      name: 'Sales & Marketing',
      summary:
        'Current roles: Sales Head. Function description to be confirmed by HR.',
    },
    {
      name: 'Store',
      summary:
        'Current roles: Store Executive. Function description to be confirmed by HR.',
    },
  ],
  approvers: [
    {
      person: 'Hetvi Manish Shah',
      role: 'COO',
    },
    {
      person: 'Archit Rajeev Khandelwal',
      role: 'CSO',
    },
    {
      person: 'Visat Subodh Patel',
      role: 'CEO',
    },
    {
      person: 'Akhilesh Parashram Thorat',
      role: 'CTO',
    },
    {
      person: 'Rajdip Saha',
      role: "Founder's Office Lead",
    },
    {
      person: 'Niyazuddin Sarfuddin Khan',
      role: 'Hardware Team Lead',
    },
    {
      person: 'Ambadas Shivsharan Sangoli',
      role: 'Sales Head',
    },
    {
      person: 'Trupti Minil Awade',
      role: 'Senior HR Generalist',
    },
    {
      person: 'Ozair M Salim Khatri',
      role: 'Senior Engineering Manager',
    },
    {
      person: 'Tushar Sharad Shelke',
      role: 'SR. Finance Executive',
    },
    {
      person: 'Kapil Prahlad Kumavat',
      role: 'Finance Controller',
    },
  ],
  evidence: [],
  history: [
    {
      version: '0.2',
      date: '2026-09-03T00:00:00.000Z',
      by: 'Requested leadership update',
      description:
        'Added Company Board governance and confirmed CEO, CTO, COO and CSO reporting hierarchy.',
    },
    {
      version: '0.1',
      date: '2026-09-02T12:48:37.136Z',
      by: 'Initial source import',
      description:
        'Imported supplied active and inactive CSVs. October functions retained as proposals. Uncertain records require HR review.',
    },
  ],
};
